
services:
  bechdelproxy:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: bechdelproxy
    ports:
      - "80:1789"
    volumes:
      - .:/app
    command: air
    environment:
      PGSQL_HOST: db
      PGSQL_PORT: 5432
      PGSQL_USER: postgres
      PGSQL_PASS: postgres
      PGSQL_DB: mydb
      LOG_LEVEL: DEBUG
    depends_on:
      - db

  db:
    image: postgres:16.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
